name: Alexander M Wolff - Visual Storyteller
markdown: kramdown
port: 7000
# permalink: /blog_entries/:year/:month/:day/:title
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
